default: &local_defaults
  timeout: 5000
  adapter: postgresql
  host: localhost
  port: 5432
  min_messages: warning
  encoding: utf8
  username: lee
  password:

development: &development
  <<: *local_defaults
  database: supply_side_dev
  template: template0

development_cached:
  <<: *development

test:
  <<: *local_defaults
  database: supply_side_test<%= ENV['TEST_ENV_NUMBER'] %>
  template: template0

production:
  <<: *development